
---
title: "Graphics for Question 2 - Interpretation 1"
output: html_document
---

**Loading packages**



```{r}

library(dplyr)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(forcats)
library(vcd)
library(igraph)
library(ggplot2)
library(ggnetwork)
library(ggraph)
library(rmarkdown)
library(viridis)

```


**Count of fatalities per year**

```{r echo=TRUE, message=FALSE, warning=FALSE}

df_nigeria_fat_distu <- df_pink |> group_by(year, fatalities) |> 
      summarise(n = n(), .groups = "drop") |>
      mutate(fat_case = fatalities * n) |>
      group_by(year) |> summarise(Anzahl = sum(fat_case))

# Plotting     

    ggplot(df_nigeria_fat_distu, aes(x = year, y = Anzahl)) +
      geom_bar(stat = "identity", fill = viridis(1, option = "cividis"), colour = "black") +
      labs(title = "Count of fatalities per year",
                x = "Year",
                y = "Count of fatalities") +
       theme( panel.background = element_rect(fill = "white", colour = NA), 
             plot.background = element_rect(fill = "white", colour = NA),
             panel.grid.major = element_line(color = "grey80"),  # Graue Haupt-Rasterlinien
             panel.grid.minor = element_line(color = "grey90"),
             axis.title = element_text(size = 13, face = "bold"),  
              axis.text = element_text(size = 9, face = "bold"),
              plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
              strip.text = element_text(size = 9, face = "bold") 
      ) 
```


**Count of conflicts over time**

```{r echo=TRUE, message=FALSE, warning=FALSE}

# Analysing 

df_nigeria_evt_count <- df_pink |> group_by(year) |>
      summarise(n = n(), .groups = "drop")

# Plotting 

    ggplot(df_nigeria_evt_count, aes( x = year , y = n)) +
      geom_bar(stat = "identity", fill = viridis(1, option = "cividis"), colour = "black") + 
      labs(title = "Count of conflicts over time",
                x = "Year",
                y = "Count of conflicts ") +
      theme( panel.background = element_rect(fill = "white", colour = NA), 
             plot.background = element_rect(fill = "white", colour = NA),
             panel.grid.major = element_line(color = "grey80"),  # Graue Haupt-Rasterlinien
             panel.grid.minor = element_line(color = "grey90"), 
             axis.title = element_text(size = 13, face = "bold"),  
             axis.text = element_text(size = 9, face = "bold"),
             plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
             strip.text = element_text(size = 9, face = "bold") 
      )
    

``` 

*Fatilities to Battel Ratio by event-type over time*

```{r echo=TRUE, message=FALSE, warning=FALSE}

# Analysing 

    df_nigeria_fat_ratio <- df_pink |>
      group_by( year, fatalities) |> 
      summarise(n = n(), .groups = "drop") |>  mutate(fat_case = fatalities * n) |>
      group_by(  year) |> summarise(ye = sum(fat_case), total = sum(n)) |>
      mutate(ratio = ye/total)|> 
      ungroup() 

# Plotting 

       ggplot(df_nigeria_fat_ratio, aes( x = year , y = ratio)) +
                   geom_bar(stat = "identity", fill = viridis(1, option = "cividis"), colour = "black") +
                   labs(title = "Ratio of Fatalities to Conflicts over time",
                                        x = "Year",
                                        y = "Ratio") +
                   theme( panel.background = element_rect(fill = "white", colour = NA), 
                          plot.background = element_rect(fill = "white", colour = NA),
                          panel.grid.major = element_line(color = "grey80"),  # Graue Haupt-Rasterlinien
                          panel.grid.minor = element_line(color = "grey90"),
                          axis.title = element_text(size = 13, face = "bold"),  
                          axis.text = element_text(size = 9, face = "bold"),
                          plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
                          strip.text = element_text(size = 9, face = "bold") 
                          )
```


*Measuring the intensity of conflicts based on fatalities over time*.

```{r echo=TRUE, message=FALSE, warning=FALSE}

# Analysing 

df_nigeria_fat_distu <- df_pink |> group_by(event_type, year, fatalities) |> 
  summarise(n = n(), .groups = "drop") |>
  mutate(fat_case = fatalities * n) |>
  group_by(year, event_type) |> summarise(Anzahl = sum(fat_case))

# Plotting 
  ggplot(df_nigeria_fat_distu, aes(x = year, y = Anzahl)) +
       geom_bar(stat = "identity", fill = viridis(1, option = "cividis"), colour = "black") +
       facet_wrap(~ event_type, scales = "free_y")+
       labs(title = "Fatalities by event type over time",
                x = "Year",
                y = "Count of Fatalities") +
       theme( axis.title = element_text(size = 13, face = "bold"),  
             axis.text = element_text(size = 9, face = "bold"),
             plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
              strip.text = element_text(size = 9, face = "bold") 
      )
```
